import { createApp } from "./app";
import { createClient } from "redis";
import { readConfig } from "./config";
import { createDb } from "./db";
import { RssService } from "./rss";
import { ScrapingService } from "./scraping";
import { SourceCollector, CollectionService } from "./collection";
import { UserCollectionLock } from "./lock";
import { startScheduler } from "./scheduler";
const config = readConfig();
const db = createDb(config.DATABASE_URL);
const redis = createClient({ url: config.REDIS_URL });
redis.on("error", () => console.error("Redis connection error"));
await Promise.all([db.$connect(), redis.connect()]);
const runner = new CollectionService(db, new SourceCollector(db, new RssService(), new ScrapingService()), new UserCollectionLock(redis));
const stopScheduler = startScheduler(db, runner);
const server = createApp(db, redis, config, { runner }).listen(config.PORT, () => console.info(`DailyBrief listening on port ${config.PORT}`));
async function shutdown() { stopScheduler(); server.close(); await Promise.all([db.$disconnect(), redis.quit()]); process.exit(0); }
process.on("SIGTERM", shutdown);
process.on("SIGINT", shutdown);
